cronJob:
  image: registry.redhat.io/openshift4/ose-cli:latest
  restartPolicy: OnFailure # Optional
  schedule: "*/5 * * * *"
  serviceAccount: default # Optional
  script: |
    #!/bin/bash
    oc get pods
