cronJob:
  image: registry.access.redhat.com/ubi8:latest
  restartPolicy: OnFailure # Optional
  schedule: "*/1 * * * *"
  serviceAccount: default # Optional
  script: |
    #!/bin/bash
    echo 'Hello World!'
