cronJob:
  image: registry.redhat.io/openshift4/ose-cli:latest
  restartPolicy: OnFailure
  schedule: "*/5 * * * *"
  serviceAccount: auto-csr
  script: |
    #!/bin/bash
    GO_TEMPLATE='{{`{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}`}}'
    PENDING_CSRS=$(oc --insecure-skip-tls-verify=true get csr -o go-template="$GO_TEMPLATE")
    if [[ -n $PENDING_CSRS ]] ; then
      oc --insecure-skip-tls-verify=true adm certificate approve $PENDING_CSRS
    else
      echo "Nothing to approve!"
    fi
